### ISSUE TITLE
EPIC Koppelingen - Veldcodes voor Zaaksysteem [STuF-Koppeling]

### ISSUE THREAD

**Issue by StefSchots1993** [Dimpact-Samenwerking/Open-Formulieren#1]
Omschrijving
Een aantal vooraf gedefinieerde velden in een formulier-inzending moeten kunnen landen in een zaaksysteem zoals KCS van Exxelence [noot: nog meer systemen noemen?].
Bijvoorbeeld: De achternaam van een indiener moet direct landen in het ‘achternaam’-veld van het zaaksysteem.

Hoe regel je dit in OF?
Op de tab Registratie van een veld selecteer je het door Maykin geprogrammeerde Registratie-attribuut horend bij de waarde van dat veld. ‘Achternaam (van de indiener)’ heeft bijvoorbeeld registratie-attribuut ‘Initiator > Geslachtsnaam’

Momenteel (9 juni 2022) zijn er slechts 5 registratie-attributen gedefinieerd. Dat moeten er veel meer worden. Het gaat om:
• Persoonsgegevens van indiener en betrokkenen (contactpersonen, gemachtigden, derde partijen en overige personen)
• Adresgegevens (van bovenstaande personen en locaties)
• Bijzondere (extra) gegevens zoals toelichting- en omschrijvingsveld.
Ons concrete voorstel staat in de bijlage.
Toegevoegde waarde
Door formulieren ‘met veel automatisch ingevulde details’ te laten landen in het zaaksysteem kan een formulier makkelijker gekoppeld worden aan persoons- en locatiegegevens.
Dat levert een snellere afhandeling van hogere kwaliteit op, zowel voor indiener als behandelaar doordat een deel van het werk (het vullen van bepaalde velden) automatisch en direct gedaan wordt (versus handmatig en achteraf).

Voorstel in de bijlage
[Wijzigingsverzoek Ontwikkeltafel OF.1.docx](https://github.com/Dimpact-Samenwerking/Open-Formulieren/files/8938678/Wijzigingsverzoek.Ontwikkeltafel.OF.1.docx)

**Comment by Hedda-van-Ooijen** [comment]
**Omschrijving**
Een aantal vooraf gedefinieerde velden in een formulier-inzending moeten kunnen landen in een zaaksysteem zoals KCS van Exxelence [noot: nog meer systemen noemen?]. 
Bijvoorbeeld: De achternaam van een indiener moet direct landen in het ‘achternaam’-veld van het zaaksysteem.

**Hoe regel je dit in OF?**
Op de tab Registratie van een veld selecteer je het door Maykin geprogrammeerde Registratie-attribuut horend bij de waarde van dat veld. ‘Achternaam (van de indiener)’ heeft bijvoorbeeld registratie-attribuut ‘Initiator > Geslachtsnaam’
 
Momenteel (9 juni 2022) zijn er slechts 5 registratie-attributen gedefinieerd. Dat moeten er veel meer worden. Het gaat om:
•	Persoonsgegevens van indiener en betrokkenen (contactpersonen, gemachtigden, derde partijen en overige personen)
•	Adresgegevens (van bovenstaande personen en locaties)
•	Bijzondere (extra) gegevens zoals toelichting- en omschrijvingsveld.
Ons concrete voorstel staat in de bijlage.
Toegevoegde waarde
Door formulieren ‘met veel automatisch ingevulde details’ te laten landen in het zaaksysteem kan een formulier makkelijker gekoppeld worden aan persoons- en locatiegegevens. 
Dat levert een snellere afhandeling van hogere kwaliteit op, zowel voor indiener als behandelaar doordat een deel van het werk (het vullen van bepaalde velden) automatisch en direct gedaan wordt (versus handmatig en achteraf).

Voorstel in de bijlage
[Wijzigingsverzoek Ontwikkeltafel OF.1.docx](https://github.com/Dimpact-Samenwerking/Open-Formulieren/files/8938678/Wijzigingsverzoek.Ontwikkeltafel.OF.1.docx)

**Comment by Hedda-van-Ooijen** [comment]
Op vrijdag 24 juni overleg gehad met Joeri en Jelle (onze techn. projectleider). Joeri gaat de registratiecodes voor indiener (initiator)  en locatie,  samen met een veld voor omschrijving en toelichting in OF zetten. Dat zal medio/eind juli gerealiseerd zijn.

Voor het beschikbaar maken van de betrokkenen-rollen (zoals contactpersoon, gemachtigde, derde partij en overig ) gaat hij contact opnemen met @StefSchots1993 omdat daar extra werk aan zit.

**Comment by joeribekker** [comment]
We gaan hiermee rollen configureerbaar maken in OF, zodat je velden kan koppelen aan zaak-betrokkenen.

Eigenlijk is dit invulling van deze: https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/relatieklasse/rol

**Comment by joeribekker** [comment]
Initiator velden worden gedaan via https://github.com/open-formulieren/open-forms/issues/1867

De overige velden moeten nog.

**Comment by joeribekker** [comment]
In 2.0.0 komen de initiator-velden erin. Ik durf nog niet te zeggen of we de wijzigingen ook doorvoeren op 1.1.x.

Locatie velden kon ik niet direct vinden in StUF.

**Comment by joeribekker** [comment]
Goed nieuws: De extra velden zijn ook doorgevoerd in 1.0.x en 1.1.x!

**Comment by StefSchots1993** [comment]
@Hedda-van-Ooijen - Zoals maandag besproken in het wijzigingstafeloverleg is dit reeds opgepakt. De generieke veldcodes zijn opgenomen en de overige veldcodes gaan jullie specifiek in het koppelvlak met de makelaar oppakken. Bij deze sluit ik dit issue voor nu..

**Comment by Hedda-van-Ooijen** [comment]
prima

Van: Stef Schots ***@***.***>
Verzonden: vrijdag 28 oktober 2022 10:34
Aan: Dimpact-Samenwerking/Open-Formulieren ***@***.***>
CC: Ooijen, Hedda van ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Dimpact-Samenwerking/Open-Formulieren] EPIC Koppelingen - Veldcodes voor Zaaksysteem [STuF-Koppeling] (Issue #1)


@Hedda-van-Ooijen<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHedda-van-Ooijen&data=05%7C01%7CHM.van.Ooijen%40leidschendam-voorburg.nl%7C2a876911c235450a343f08dab8bf18c4%7Ccf0a98cbb2914eaa924dec1d7359cb8f%7C0%7C0%7C638025428158692725%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CUUO9RzbA12hSgkjedsxcQGGBYcw5ZRmP12pCEp4tRQ%3D&reserved=0> - Zoals maandag besproken in het wijzigingstafeloverleg is dit reeds opgepakt. De generieke veldcodes zijn opgenomen en de overige veldcodes gaan jullie specifiek in het koppelvlak met de makelaar oppakken. Bij deze sluit ik dit issue voor nu..

-
