### ISSUE TITLE
Definitie mapping  productaanvraag naar e-Suite: MVP

### ISSUE THREAD

**Issue by PaskalKiers** [Dimpact-Samenwerking/Open-Formulieren#108]
"***Als*** PO PodiumD
***wil ik*** wil ik de verwerkte data van een attribuut uit de productaanvraag omgezet wordt naar het format van dat attribuut in de e-Suite
***zodat*** deze waarden in de e-Suite verwerkt kunnen worden, zonder dat er aanpassingen nodig zijn in de zaaktypeinrichting.

Aanvullende opmerkingen: 
Oplossingsrichting: de verwerking moet in e=Suite opgelost werk voor Andy
#3"

Dit is de minimale uitwerking van #114 , om de integratie van e-suite en OF mogelijk te maken zolang er nog onvoldoende kaders zijn vastgesteld op platform cq landelijk niveau.

**Comment by PaskalKiers** [comment]
Specifieke situatie bij #104 : is dit überhaupt haalbaar?

**Comment by joeridiederen** [comment]
@PaskalKiers ; dit voelt als een doublure van dimpact-samenwerking/open-formulieren#104

**Comment by PaskalKiers** [comment]
Ik denk mijn gebrek aan kennis. Ik sluit deze, voegt weinig toe, behalve een wat minder technische beschrijving van de wens.
