### ISSUE TITLE
EPIC Formulieren overzicht - Onderhoudsmodus formulieren

### ISSUE THREAD

**Issue by StefSchots1993** [Dimpact-Samenwerking/Open-Formulieren#11]
Als gebruiker wil ik **een selectie** van formulieren **In één keer** in onderhoudsmodus kunnen zetten.
Als gebruiker wil ik **voor die specifieke selectie** een **zelf in te stellen** onderhoudsboodschap kunnen tonen.

Voorbeeld: Ik wil met een actie alle formulieren, waarbij DigiD als authenticatiemiddel wordt gebruikt in onderhoudsmodus kunnen zetten en met daarbij een boodschap dat het formulier tijdelijk niet te gebruiken is in verband met onderhoud aan DigiD.

**Comment by Hedda-van-Ooijen** [comment]
Voor ingevuld format zie issue 6
