### ISSUE TITLE
Sjablonen - Logo toevoegen aan samenvattings PDF inzending

### ISSUE THREAD

**Issue by StefSchots1993** [Dimpact-Samenwerking/Open-Formulieren#12]
_**- Probleembeschrijving/Organisatiebehoefte**_

_**- Op welke onderdelen en/of schermen heeft het verzoek betrekking?**_

_**- Mogelijke oplossingsrichtingen**_

_**- Wijze van totstandkoming**_

_**- Geef aan welke waarde de wijziging toevoegt voor de bedrijfsvoering**_

**_- Geef aan welke waarde de wijziging toevoegt voor de dienstverlening_**

Als gemeente zou ik graag een eigen logo willen kunnen toevoegen aan het sjabloon voor zowel de:
Bevestigingsmail, de bevestigingspagina, als de bijbehorende bevestiging PDF met de inzending.

**Comment by HarmkeH** [comment]
Deze is al gerealiseerd.

**Comment by StefSchots1993** [comment]
Dan zet ik deze op Closed.
