### ISSUE TITLE
Relatie productaanvraag en zaak

### ISSUE THREAD

**Issue by PaskalKiers** [Dimpact-Samenwerking/Open-Formulieren#163]
"Als informatiebeheerder
wil ik dat een productaanvraag niet later vernietigd wordt dan de bijbehorende zaak
zodat alle zaakinformatie op tijd vernietigd wordt.

Acceptatiecriteria:

Iig Van toepassing op eSuite.
Bovenliggende story van IB is nog niet geregistreerd.

https://github.com/Dimpact-Samenwerking/PodiumD/issues/193

**Comment by PaskalKiers** [comment]
Afgesproken is dat voor de eSuite OF koppeling een productaanvraag vernietigd wordt zodra de informatie uit de productaanvraag is vastgelegd in een zaak in een zaakdossier.

Dit kan omdat alle informatie uit de productaanvraag in de eSuite wordt overgenomen.

**Comment by joeridiederen** [comment]
@PaskalKiers volgens mij een doublure van dimpact-samenwerking/open-formulieren#121

**Comment by PaskalKiers** [comment]
Story #121 aangepast met tekst van #163.  #121 was oplossingsvraag.   Het is uiteindelijk een andere oplossing geworden die wel aansluit bij de behoefte zoals beschreven in #163
.
