### ISSUE TITLE
Feedback tools GovMetric en Siteimprove

### ISSUE THREAD

**Issue by StefSchots1993** [Dimpact-Samenwerking/Open-Formulieren#4]
Tools om feedback te kunnen geven, waaronder minimaal GovMetric en Siteimprove, kunnen zonder tussenkomst van de leverancier door de gebruiker van de toepassing eenvoudig worden toegevoegd en geactiveerd.

Was origineel onderdeel van het PVE maar heeft het niet gehaald.
Eis: Algemeen 6.
Zie ook NvI: 133

Input van gemeente nodig

Relevante GovMetric documentatie
Relevante SiteImprove modules/documentatie Werkt reeds, getest met RID.
Verduidelijking

[Feedbacktool Siteimprove.docx](https://github.com/open-formulieren/open-forms/files/6883694/Feedbacktool.Siteimprove.docx)

https://www.drupal.org/project/siteimprove
https://help.siteimprove.com/support/solutions/articles/80000448448-adding-siteimprove-analytics-javascript-to-your-website

Actie van Gemeenten
Documentatie nodig van GovMetric

Haarlemmermeer gebruikt de feedback optie van Siteimprove en kunnen specs aanleveren (Attilla Vigh).
Noordoostpolder, zou destijds via Bas v Rens documentatie m.b.t. GovMetrics opvragen.

**Comment by StefSchots1993** [comment]
Maykin vragen wat ze nodig hebben.

**Comment by Hedda-van-Ooijen** [comment]
Format ingevuld: 
Thema: Koppelvlakken?

**Omschrijving**
•	Als inwoner wil ik middels een feedback-tool tijdens het invullen en vanaf het bevestigingsscherm van het formulier (anoniem) feedback kunnen geven over mijn ervaringen.
•	Als bouwer wil ik per formulier de optie ‘feedback toestaan’ aan of uit kunnen zetten

Gebruikelijke feedback-tools: GovMetrics (Klant-in-Focus aka smileys) _[ Noot Hedda: zijn er nog meer varianten?)_

**GovMetrics:**

- Er worden na afloop 3 smileys op het bevestigingsscherm getoond met een uitnodiging om te reageren (zie bijlage)
- Bij iedere keuze opent een toelichtingsscherm (zie bijlage)
- Na verzenden verschijnt een bedankje (zie bijlage)
 
_Noot Hedda:_ 
•	Moeten de teksten onder de smileys in OF aangepast kunnen worden of gebeurt dat in GovMetrics?
•	Worden de teksten van de toelichting en bedankje beheerd in GovMetrics of OF?

**Toegevoegde waarde**
•	Als invuller kan ik makkelijk mijn mening geven over een digitaal formulier
•	Als bouwer kan ik makkelijk smileys aan- of uitzetten in het formulier
•	Als beheerder kan ik statistieken oproepen over de feedback van de indieners

**
![Smileys toelichtingsveld](https://user-images.githubusercontent.com/83342686/174626513-2c2405cf-dbe5-4922-a706-3c4834b91e90.jpg)
![Smileys](https://user-images.githubusercontent.com/83342686/174626516-576f10e2-685e-41aa-bcfd-d4c53dce9bbf.jpg)
![Smileys bedankje](https://user-images.githubusercontent.com/83342686/174626506-be4b5647-ac04-4e34-a606-a1eec65ef168.jpg)**
Wat hebben jullie nodig om te regelen dat gemeenten smileys kunnen activeren per formulier

**Comment by StefSchots1993** [comment]
Opgelost en opgenomen om meet te gaan in V2.1.0.
