### ISSUE TITLE
Hergebruik van waarden - Hergebruik van waarden in alle daarna volgende attributen

### ISSUE THREAD

**Issue by GeertDonkers** [Dimpact-Samenwerking/Open-Formulieren#50]
Als formulierbouwer wil ik de waarden van alle waarden zoals formuliervelden, objectregistraties, parameters, variabelen, systeemparameters, zaakgegevens, et cetera, kunnen hergebruiken in alle daarna-volgende attributen en condities, zodat ik context kan toevoegen aan het formulier. 

Voorbeeld: ‘Van welke periode wilt u uw specificatie toevoegen: kies uit combobox [maand]’. Volgend scherm: Voeg hier uw specificatie van [maand] toe.

**Comment by GeertDonkers** [comment]
Is in essentie onderdeel van Variabelen-Epic Den Haag: ieder veld wordt een variabele. Waarde kan op andere plekken hergebruikt worden. Alles dat ge-prefilled kan worden komt ook in een variabele terecht.

**Comment by StefSchots1993** [comment]
Opgeleverd in 2.3.0.
