### ISSUE TITLE
Indienen - Versturen formulieren met BSN-prefill mislukt met de melding 'Call did not validate on the backend'

### ISSUE THREAD

**Issue by hlmr-erik** [Dimpact-Samenwerking/Open-Formulieren#60]
Wanneer je een formulier probeert te verzenden waarvan de gegevens zijn gepre-filled met die van een BSN-testaccount, mislukt het verzenden van het formulier met de melding 'Call did not validate on the backend'. Als ik in de dev-tools kijk, zie ik dat het de velden voor postcode en geboortedatum als onjuist beoordeelt: invalidPrefilledFields":["Geboortedatum", "Postcode"]

De velden tonen geen validatie-fouten in het formulier zelf:
https://user-images.githubusercontent.com/111565013/185928847-9aaee2c4-d13f-4e27-a42c-4fae4fca114b.png

Wanneer de velden bewerkbaar worden gemaakt, en een andere (willekeurige) geboortedatum en postcode wordt gekozen, word het formulier wel succesvol verzonden. Het lijkt er dus op dat een deel van de gegevens afkomstig van de prefill niet goed genormaliseerd wordt - wat wel gebeurt als het veld handmatig wordt ingevuld?

Stappen om te reproduceren:

1.     Open het formulier https://haarlemmermeer.test.open-formulieren.nl/prefill-test-bsn
2.     Gebruik 900174341 of 900174316 als BSN
3.     Vul de twee verplichte velden in
4.     Probeer het formulier te versturen.

**Comment by hlmr-erik** [comment]
Gerelateerde story op de GitHub van OpenForms: https://github.com/open-formulieren/open-forms/issues/1899

**Comment by StefSchots1993** [comment]
Is reeds gefixed in V2.0.1.
