### ISSUE TITLE
Formulier editor - OpenForms bij het importeren van formulieren identieke formulierdefinities laten herkennen / samenvoegen

### ISSUE THREAD

**Issue by hlmr-erik** [Dimpact-Samenwerking/Open-Formulieren#62]
Als ik twee formulieren exporteer, die beide de formulierdefinitie 'Stap1' delen - en ze vervolgens importeer in een nieuwe OpenForms omgeving - dan worden er twee aparte formulierdefinities met de naam 'Stap1' aangemaakt. 

Bijvoorbeeld, deze definities genaamd 'Uw gegevens' zouden hetzelfde zijn (en gedeeld/hergebruikt worden) in de oorspronkelijke omgeving - maar verschijnen afzonderlijk wanneer ze geëxporteerd en vervolgens geïmporteerd worden:
![image](https://user-images.githubusercontent.com/111565013/185950060-73aa7a65-050a-449d-8ff5-95058c884f50.png)

Gewenst gedrag:
Dat OpenForms identieke (herbruikbare) formulierstappen zou herkennen. 
Dit kan dmv. een hash, in welk geval er geen kans is op overschrijven (omdat de formulierdefinities gegarandeerd identiek zijn). Alternatief op ID; Bij het herkennen van dubbele formulierstappen op ID kunnen de opties 'Beide versies apart houden', 'Samenvoegen en versie A behouden' of 'Samenvoegen en versie B behouden' aangeboden worden.

**Comment by hlmr-erik** [comment]
Gerelateerde story op de GitHub van OpenForms: https://github.com/open-formulieren/open-forms/issues/1906

**Comment by StefSchots1993** [comment]
Op basis van reactie van Sergei sluit ik deze hier ook.
