### ISSUE TITLE
Formulier editor - Datum component - Geen mogelijkheid met een bewegende min/max range

### ISSUE THREAD

**Issue by hlmr-dave** [Dimpact-Samenwerking/Open-Formulieren#69]
Thema 
Validatie op lopende datums

Omschrijving
We willen een datum validatie die controleert op [vandaag] [+ of -]  [1 dag / 1 week / 1maand]. Nu is het alleen nog maar fixed in te stellen.

Toegevoegde waarde voor bedrijfsvoering
Betere validatie en uitval van gebruikers vooraf dan achteraf. 

Toegevoegde waarde voor de dienstverlening
Betere validatie en uitval van gebruikers vooraf dan achteraf.

**Comment by hlmr-erik** [comment]
Deze is al opgepakt: https://github.com/open-formulieren/open-forms/issues/1878

**Comment by hlmr-dave** [comment]
Deze is al opgepakt
