### ISSUE TITLE
Vrije tekst component - Ingestelde grootte van plaatjes wordt niet gerespecteerd

### ISSUE THREAD

**Issue by hlmr-erik** [Dimpact-Samenwerking/Open-Formulieren#70]
Bij het instellen van de grootte van een plaatje via de GUI van de 'vrije tekst' component...
![image](https://user-images.githubusercontent.com/111565013/185931091-463b7c1c-2bb8-4d6d-8718-33d319d6bfd5.png)

Wordt dit gerespecteerd in de form-editor view:
![image](https://user-images.githubusercontent.com/111565013/185931171-610fd079-86f7-4748-a90e-68b8d283cc6f.png)

Maar niet in het formulier zelf:
![image](https://user-images.githubusercontent.com/111565013/185931232-b27ce106-148b-4236-a650-ee31072bd319.png)

**Comment by hlmr-erik** [comment]
Gerelateerde story op de GitHub van OpenForms: https://github.com/open-formulieren/open-forms/issues/1901

**Comment by StefSchots1993** [comment]
Is een bug en wordt volgens mij al door Maykin opgepakt, maak ik op uit 1901.
@hlmr-erik mag ik deze vast sluiten?

**Comment by hlmr-erik** [comment]
@StefSchots1993 Ik zie het; dat is prima.
