### ISSUE TITLE
Object - Registratie - Metadata uitbreiden

### ISSUE THREAD

**Issue by joeridiederen** [Dimpact-Samenwerking/Open-Formulieren#84]
Thema 
- De metadata die aan een object 'productaanvraag' wordt toegevoegd nadat de klant een formulier heeft ingediend.

Omschrijving
- Op dit moment bestaat het object 'productaanvraag' uit niets meer dan label:value-pairs. Die data is niet toereikend om effectief data te hergebruiken. Dat speelt op meerdere vlakken;

**Type data toevoegen**
Het is de raadpleger van het object niet duidelijk of een cijfer in een number-veld is gevuld, of onderdeel is van een string. De juiste typering van deze data is voorwaardelijk om bijvoorbeeld te kunnen rekenen. We pleiten voor een - liefst landelijk - vastgestelde methode om bepaalde type data te categoriseren.

**Label opslaan**
Op dit moment bestaat de entry in het object uit; label:value, waarbij label verwijst naar het ID van het attribuut, in Open Formulieren 'eigenschapnaam' genoemd. Dit ID is niet mooi te presenteren voor de behandelaar. Verzoek is om het door de klant zichtbare label van een attribuut ook op te slaan in het object.

**Voertaal klant leidend bij opslag**
Als aan bovenstaande wordt voldaan is het relevant om de opslag in het object te vullen met de zichtbare labels behorende bij de voertaal van de klant.

**Comment by joeridiederen** [comment]
Relatie met https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/57

**Comment by joeridiederen** [comment]
@joeribekker ; Deze wil ik graag ook in BZK-verband apart benoemen.

**Comment by joeribekker** [comment]
> Type data toevoegen

Ik heb hier al een voorstel voor gedaan in combinatie met "Productaanvraag".

Als je een productaanvraag definieert, dan leg daarin precies vast hoe het object (objecttype met veldtypen dus) er uit komt te zien. Dit is echter niet dynamisch: Je kan niet zomaar vanuit je formulier een tekstveld toevoegen, die dan met type en al wordt opgenomen in het object.

Dat laatste kan technisch wel, maar het zorgt ervoor een object onvoorspelbaar wordt qua data, en ik ben daar niet zo'n voorstander van.

Als je dat wilt, dan heb je straks label, basistype, formaat, min-length, max-length, hints e.d. nodig om het bruikbaar te maken. Ter illustratie: 

* label: "Uw burgerservicenummer"
* basistype: "string"
* formaat: [0-9]+
* min-length: 9
* max-length: 9
* hint: "bsn" (zodat een systeem weet dat het met dit attribuut een persoon kan opzoeken)

Je kopieert dan bijna alle mogelijkheden van **JSON schema** naar JSON. Een andere partij had hiernaast zelfs nog eens HTML-specifieke attributen toegevoegd: html-ID, html-weergave, html-kleur... etc.

Ik ben dus voorstander van JSON-schema gebruiken maar dat impliceert ook dat je dus van te voren goed moet nadenken hoe het object er uit komt te zien.

> Label opslaan

Ook dit zit in JSON-schema, het "title" attribuut. Ik zou dat niet bij het object willen opslaan. Dit is een technische keuze en functioneel zou het niet uit moeten maken.

**Comment by joeridiederen** [comment]
Tnx voor je reactie @joeribekker ; we gaan een proeftuin inrichten om de impact van het strak inrichten van het JSON schema te duiden. To be continued.

**Comment by PaskalKiers** [comment]
Gerelateerd aan #108

**Comment by joeridiederen** [comment]
Met de kennis van nu afgesloten.
