### ISSUE TITLE
[Epic] - [Betaling] - [Productaanvraag aanmaken na betaling]

### ISSUE THREAD

**Issue by joeridiederen** [Dimpact-Samenwerking/Open-Formulieren#97]
Thema 
- Betaling

Omschrijving
- Als organisatie wil ik dat het object 'productaanvraag' pas wordt gecreëerd na het doorlopen van een betaling, zodat het object vanaf het ontstaan de actuele betaalstatus bevat 

Toegevoegde waarde voor bedrijfsvoering
- Ik kan de betaalstatus mappen naar input voor het zaaksysteem, zodat de behandelaar de actuele status van de betaling bij de zaak ziet.

**Comment by joeridiederen** [comment]
Hi @StefSchots1993; ik ben even benieuwd naar de workflow achter deze back log. Dit ticket willen we graag bespreken met Maykin, want is blokkerend voor ingebruikname OF. Ik hoor graag of dit de juiste route is, of dat we het direct bij Maykin zullen adresseren?

**Comment by StefSchots1993** [comment]
@joeridiederen  - Van origine was het, het idee dat we vanuit deze backlog items zouden bespreken in de Wijzigingstafel Open Formulieren, om deze vanuit daar, met instemming van de "OF-afnemers" vanuit Dimpact, en in opdracht van diezelfde groep, in te dienen ter ontwikkeling bij de Leverancier. Echter is de realiteit toch weerbarstiger dan dat vanwege verschillende oorzaken. Maar in het kort zie ik dit verzoek ook even als onderdeel van hetgeen we vorige week besproken hebben.

En in het kort, er is nu geen "in beton gegoten" workflow voor deze items.

**Comment by PaskalKiers** [comment]
opgenomen in Dimpact-Samenwerking/Open-Formulieren#113

**Comment by joeridiederen** [comment]
Gesloten
