### ISSUE TITLE
Registratie - Specificeren locatie MS Graph

### ISSUE THREAD

**Issue by HarmkeH** [Dimpact-Samenwerking/Open-Formulieren#99]
**Thema** 
- Registratie MS Graph

**Omschrijving**
- Wij willen zelf de locatie generiek (eventueel per formulier, is niet noodzakelijk) specificeren binnen de huidige plugin MS Graph. 
- Plugin MS Graph
- Toevoegen extra veld voor locatie in configuratie plugin.

**Toegevoegde waarde voor bedrijfsvoering**
We kunnen formulieren op een besloten Sharepointlocatie registreren. En daarna gerobotiseerd verder verwerken. Formulieren liggen daardoor binnen enkele minuten bij de afhandelaar in plaats van binnen 1 werkdag.

**Toegevoegde waarde voor de dienstverlening**
De indiener heeft sneller een reactie op de aanvraag omdat het formulier direct bij de afhandelaar ligt.

**Comment by StefSchots1993** [comment]
Lijkt intussen te zijn opgelost in 2.1.0

**Comment by StefSchots1993** [comment]
Opgelost door https://github.com/open-formulieren/open-forms/pull/2526
